name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"    # every 6 hours
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: OmeshThokchom
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
