name: Generate Snake Animation

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: OmeshThokchom
          outputs: |
            dist/github-contribution-grid-snake.svg
    outputs:
      snake: dist/github-contribution-grid-snake.svg

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
